model:
  model_type: 'GCNConv'
  hidden_encoder_embed: 64
  hidden_GCN_embed: 64
  encoder_out: 64
  allow_loops: True
  #linear, long
  emb_type: 'long'
  div_val: 2
  #none, only_train, only_param, full
  pos_embed: 'none'
  depth: 2
  #Experiment with long embed
  num_blocks: 3
  iso_amount: 16
  is_edges_trainable: True
  suffix: log

train_params:
  batch_size: 60
  device_num: 3
#  'online', 'offline', 'disabled'
  wandb_mode: 'online'
# CURRENT ON LOGS DATA
files_params:
  save_root: '/raid/data/chest_xray/'
  path_to_files: '/raid/data/chest_xray/preprocessed_xray/*/*.npy'

exp_name: 'Isoclines'
